server:
  port: 20001

spring:
  security:
    user:
      name: cloud
      password: cloud
  application:
    name: cloud-auth
  cloud:
    nacos:
      # 注册中心
      discovery:
        server-addr: http://192.168.198.130:8848
      # 配置中心
      config:
        server-addr: http://192.168.198.130:8848
        file-extension: yaml
        shared-configs[0]:
          data-id: cloud-auth-dev.yaml
          refresh: true

